(()=>{
const css=`
.case-study-section{margin-top:70px;padding-top:55px;border-top:1px solid var(--line)}
.case-study-intro{max-width:760px;margin-bottom:28px}.case-study-intro h3{font:600 34px 'Space Grotesk';margin:0 0 8px}.case-study-intro h3 span{color:var(--accent)}.case-study-intro p{color:var(--muted);font-size:14px;margin:0}
.case-study-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.case-study-card{padding:28px;border:1px solid var(--line);border-radius:16px;background:var(--surface);transition:.25s}.case-study-card:hover{transform:translateY(-4px);border-color:rgba(103,215,255,.45)}.case-study-card .case-kicker{font-size:9px;letter-spacing:1.5px;color:var(--accent);font-weight:800}.case-study-card h4{font:600 25px 'Space Grotesk';margin:12px 0 8px}.case-study-card p{font-size:12px;color:var(--muted);margin:0 0 18px}.case-study-metrics{display:flex;gap:14px;flex-wrap:wrap;margin:18px 0}.case-study-metrics span{font:700 13px 'Space Grotesk';color:var(--accent)}.case-study-btn,.case-study-link{display:inline-flex;padding:9px 12px;border:1px solid var(--line);border-radius:9px;font-size:10px;font-weight:800;background:transparent;color:var(--text)}.case-study-links{display:flex;gap:9px;flex-wrap:wrap;margin-top:10px}
.case-study-modal{position:fixed;inset:0;background:rgba(3,8,15,.78);backdrop-filter:blur(12px);z-index:100;display:none;align-items:center;justify-content:center;padding:24px}.case-study-modal.open{display:flex}.case-study-dialog{width:min(920px,100%);max-height:90vh;overflow:auto;background:var(--surface);color:var(--text);border:1px solid var(--line);border-radius:22px;padding:34px}.case-close{float:right;border:0;background:none;color:var(--muted);font-size:25px;cursor:pointer}.case-study-dialog h3{font:600 34px 'Space Grotesk';margin:0 0 8px}.case-study-dialog>p{color:var(--muted);font-size:13px}.architecture{margin:24px 0;padding:22px;border:1px solid var(--line);border-radius:15px;background:var(--surface2);display:grid;gap:8px;text-align:center}.architecture span{padding:10px;border:1px solid var(--line);border-radius:9px;font-size:11px;font-weight:700}.architecture i{font-style:normal;color:var(--accent);font-weight:800}.case-detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:20px}.case-detail{padding:18px;border:1px solid var(--line);border-radius:12px}.case-detail strong{display:block;font:600 16px 'Space Grotesk';margin-bottom:6px}.case-detail small{color:var(--muted);font-size:11px;line-height:1.5}
.academic-projects{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:22px}.academic-project{padding:17px;border:1px solid var(--line);border-radius:12px;background:var(--surface);display:grid;gap:6px}.academic-project span{font-size:9px;color:var(--accent);font-weight:800;letter-spacing:1.4px}.academic-project strong{font:600 17px 'Space Grotesk';color:var(--text)}.academic-project small{font-size:11px;color:var(--muted);line-height:1.5}.academic-code{display:inline!important;width:auto!important;margin-top:8px!important;padding:0!important;background:transparent!important;color:var(--accent)!important;border:0!important;border-radius:0!important;font-size:10px!important;font-weight:800!important;line-height:1.2!important}.academic-code:hover{background:transparent!important;color:var(--accent)!important;text-decoration:underline!important}.education .edu-timeline>.edu-item{display:grid!important;grid-template-columns:190px minmax(0,1fr)!important;gap:40px!important;padding:0 0 48px 35px!important;position:relative!important;background:transparent!important;color:var(--text)!important}.education .edu-timeline>.edu-item>.edu-year{grid-column:1!important;grid-row:1!important;color:var(--accent)!important}.education .edu-timeline>.edu-item>.edu-content{grid-column:2!important;grid-row:1!important;color:var(--text)!important;min-width:0!important}.education .edu-content h3{color:var(--text)!important}.education .edu-content .muted,.education .edu-content>p:not(.edu-note){color:var(--muted)!important}.education .edu-content .edu-note{font-size:11px;color:var(--muted)}
#achievements .section-heading{max-width:800px!important;margin-bottom:55px!important;color:var(--text)!important;font-size:initial!important;line-height:inherit!important;letter-spacing:normal!important;padding:0!important;background:transparent!important}
#achievements .section-heading h2{font:600 clamp(36px,5vw,58px)/1.08 'Space Grotesk'!important;letter-spacing:-2.5px!important;margin:0!important;color:var(--text)!important}
#achievements .section-heading h2 span{color:var(--accent)!important}
#achievements .section-heading .section-subtitle{color:var(--muted)!important;font-size:14px!important;max-width:650px!important;margin:18px 0 0!important}
@media(max-width:700px){.case-study-grid,.case-detail-grid,.academic-projects{grid-template-columns:1fr}.case-study-dialog{padding:24px}.education .edu-timeline>.edu-item{grid-template-columns:1fr!important}.education .edu-timeline>.edu-item>.edu-year,.education .edu-timeline>.edu-item>.edu-content{grid-column:1!important;grid-row:auto!important}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const projects={
 'Justice Unheard':['AI legal analytics platform using Flask, MySQL, NLP and Plotly for multilingual feedback, sentiment analysis, district analytics and visualization.','https://github.com/Vasumathi2002/JusticeUnheard'],
 'TECCR':['Deep multilingual NLP model for implicit Tamil cultural emotion recognition using cultural reasoning and a dual-head BiLSTM architecture.','https://github.com/Vasumathi2002/TECCR'],
 'Pulmonary Ailment Classification':['CNN-LSTM deep learning model for pulmonary ailment classification using medical signals.','https://github.com/Vasumathi2002/Pulmonary-Ailment-Classification'],
 'Residential Property Valuation':['OCR-based property valuation using OpenCV, PyTesseract and Regex to extract BHK and blueprint area/dimension information.','https://github.com/Vasumathi2002/Residential-Property-Valuation']
};
const makeProject=(name)=>`<div class="academic-project"><span>SELECTED WORK</span><strong>${name}</strong><small>${projects[name][0]}</small><a class="academic-code" href="${projects[name][1]}" target="_blank" rel="noreferrer">View code ↗</a></div>`;
function repairMalformedSectionContainment(){
  ['achievements','contact'].forEach(id=>{
    const section=document.getElementById(id); if(!section)return;
    const badAnchor=section.closest('a.academic-code');
    if(badAnchor){badAnchor.parentNode.insertBefore(section,badAnchor.nextSibling);}
  });
}
function repairEducation(){const timeline=document.querySelector('#education .edu-timeline');if(!timeline)return;timeline.innerHTML=`<article class="edu-item reveal visible"><div class="edu-year"><img class="college-logo" src="https://cdn.npfs.co/uploads/template/4018/2889/publish/images/IST-SRM-IST-logo-0sdf1.png" alt="SRM Institute of Science and Technology logo"><span>JUN 2024 — JUN 2026</span></div><div class="edu-content"><h3>M.Tech · Artificial Intelligence & Data Science</h3><p class="muted">SRM Institute of Science and Technology · 9.9 CGPA</p><p class="edu-note">Jun 2024 — Jun 2026 · Pursued alongside professional experience</p><p>Advanced study and research across machine learning, deep learning, NLP, data analytics and AI applications.</p><div class="academic-projects">${makeProject('Justice Unheard')}${makeProject('TECCR')}</div></div></article><article class="edu-item reveal visible"><div class="edu-year"><img class="college-logo" src="https://img1.pnghut.com/6/24/6/RgTxqjDtTD/area-tamil-nadu-symbol-logo-educational-institution.jpg" alt="Adhiyamaan College of Engineering logo"><span>JUL 2020 — MAY 2024</span></div><div class="edu-content"><h3>B.Tech · Information Technology</h3><p class="muted">Adhiyamaan College of Engineering · 9.3 CGPA</p><p>Undergraduate foundation in information technology, programming, software engineering and applied computing.</p><div class="academic-projects">${makeProject('Pulmonary Ailment Classification')}${makeProject('Residential Property Valuation')}</div></div></article>`}
const caseData={ai:{title:'Enterprise AI ITSM Automation',sub:'High-level architecture • Enterprise implementation',body:'Designed an AI-assisted first-response workflow to reduce repetitive L1 support effort while keeping enterprise ITSM workflows measurable and governed.',flow:['Employee / IT Request','Microsoft Copilot','AI understanding & classification','Zoho MCP / Zoho Zia','ITSM workflow automation','ServiceDesk Plus Cloud','Resolution / escalation','Analytics & CSAT'],details:[['Business challenge','High-volume repetitive L1 requests required faster first response and reduced manual handling.'],['Approach','Connected AI assistance and ITSM automation to classify, enrich and route requests through standardized workflows.'],['Outcome','98% L1 resolution-time reduction, 67% human-effort reduction and 30% ticket automation.'],['Technology','Microsoft Copilot · Zoho MCP · Zoho Zia · ServiceDesk Plus Cloud · ITSM automation']]},teccr:{title:'TECCR — Tamil Cultural Emotion Reasoner',sub:'M.Tech research • Deep multilingual NLP',body:'A deep multilingual NLP approach for recognizing implicit Tamil cultural emotions that conventional sentiment analysis can miss.',flow:['Tamil text input','Unicode validation & preprocessing','Tokenization / embeddings','Bidirectional LSTM','Cultural reasoning layer','Dual-head emotion prediction','Primary + secondary emotion'],details:[['Research focus','Implicit emotions expressed through Tamil idioms, tone, expressions and contextual cultural markers.'],['Architecture','Dual-head BiLSTM with separate softmax outputs for primary and secondary emotions, supported by cultural reasoning.'],['Reported results','Main emotions: 91.2% accuracy. Sub-emotions: 88.7% accuracy.'],['Technology','BiLSTM · NLP · Word2Vec / FastText / learned embeddings · Cultural reasoning · Python / deep learning']]}};
function openCase(key){const d=caseData[key];if(!d)return;let modal=document.querySelector('#caseStudyModal');if(!modal){modal=document.createElement('div');modal.id='caseStudyModal';modal.className='case-study-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="case-study-dialog"><button class="case-close" aria-label="Close">×</button><p class="eyebrow">CASE STUDY</p><h3>${d.title}</h3><p><strong>${d.sub}</strong></p><p>${d.body}</p><div class="architecture">${d.flow.map((x,i)=>`<span>${x}</span>${i<d.flow.length-1?'<i>↓</i>':''}`).join('')}</div><div class="case-detail-grid">${d.details.map(x=>`<div class="case-detail"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></div>`;modal.classList.add('open');document.body.style.overflow='hidden';const close=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.querySelector('.case-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()}}
function addCaseStudies(){const work=document.querySelector('#work');if(!work||document.querySelector('.case-study-section'))return;const sec=document.createElement('div');sec.className='case-study-section reveal visible';sec.innerHTML=`<div class="case-study-intro"><p class="eyebrow">04 / CASE STUDIES</p><h3>From architecture to <span>measurable impact.</span></h3><p>Deeper looks at enterprise AI automation and applied AI research, presented at a high level without exposing confidential enterprise implementation details.</p></div><div class="case-study-grid"><article class="case-study-card"><span class="case-kicker">ENTERPRISE AI • ITSM</span><h4>Enterprise AI ITSM Automation</h4><p>AI-assisted first-response automation connecting Microsoft Copilot, Zoho MCP, Zoho Zia and ServiceDesk Plus Cloud to streamline repetitive L1 support workflows.</p><div class="case-study-metrics"><span>98% faster L1 resolution</span><span>67% less human effort</span><span>30% ticket automation</span></div><button class="case-study-btn" data-case="ai">View architecture ↗</button></article><article class="case-study-card"><span class="case-kicker">M.TECH • NLP RESEARCH</span><h4>TECCR — Tamil Cultural Emotion Reasoner</h4><p>Deep multilingual NLP research for implicit Tamil cultural emotion recognition using cultural reasoning and a dual-head BiLSTM architecture.</p><div class="case-study-metrics"><span>91.2% main-emotion accuracy</span><span>88.7% sub-emotion accuracy</span></div><div class="case-study-links"><button class="case-study-btn" data-case="teccr">View architecture ↗</button><a class="case-study-link" href="https://github.com/Vasumathi2002/TECCR" target="_blank" rel="noreferrer">View GitHub ↗</a></div></article><article class="case-study-card"><span class="case-kicker">M.TECH • LEGAL AI</span><h4>Justice Unheard</h4><p>AI legal analytics platform using Flask, MySQL, NLP and Plotly for multilingual feedback, sentiment analysis, district analytics and visualization.</p><div class="case-study-metrics"><span>Multilingual feedback</span><span>Sentiment analysis</span><span>District analytics</span></div><a class="case-study-link" href="https://github.com/Vasumathi2002/JusticeUnheard" target="_blank" rel="noreferrer">View code ↗</a></article><article class="case-study-card"><span class="case-kicker">B.TECH • DEEP LEARNING</span><h4>Pulmonary Ailment Classification</h4><p>CNN-LSTM deep learning approach for pulmonary ailment classification using medical signals.</p><div class="case-study-metrics"><span>CNN-LSTM</span><span>Healthcare AI</span><span>Deep Learning</span></div><a class="case-study-link" href="https://github.com/Vasumathi2002/Pulmonary-Ailment-Classification" target="_blank" rel="noreferrer">View code ↗</a></article></div>`;work.appendChild(sec);sec.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.case)))}
function init(){repairMalformedSectionContainment();repairEducation();addCaseStudies()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();