const menu=document.querySelector('.menu');const nav=document.querySelector('#navLinks');if(menu){menu.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='76px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px 24px';nav.style.background='rgba(7,16,29,.97)';nav.style.flexDirection='column';nav.style.gap='18px';});}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));const sections=document.querySelectorAll('main section[id]');const navItems=document.querySelectorAll('#navLinks a');const setActive=()=>{let current='home';const marker=window.scrollY+140;sections.forEach(section=>{if(marker>=section.offsetTop)current=section.id;});navItems.forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+current));};window.addEventListener('scroll',setActive,{passive:true});window.addEventListener('load',setActive);navItems.forEach(link=>link.addEventListener('click',()=>{if(window.innerWidth<=850)nav.style.display='none';}));

const serviceData={
 itsm:{kicker:'IT SERVICE MANAGEMENT',title:'ITSM — Service Management',description:'Enterprise service management focused on standardized workflows, faster support and measurable service quality across business entities.',tags:['ServiceDesk Plus Cloud','Incident Management','Service Requests','L1 Automation','CSAT Analytics'],target:'#work-itsm'},
 itom:{kicker:'IT OPERATIONS MANAGEMENT',title:'ITOM — Visibility & Operations',description:'Operational visibility across infrastructure, endpoints and services through monitoring, dashboards, cloud operations and proactive management.',tags:['Site24x7','Endpoint Central','Monitoring','Cloud Migration','Infrastructure Operations'],target:'#work-itom'},
 ai:{kicker:'AI & INTELLIGENT AUTOMATION',title:'AI — Smarter IT Operations',description:'AI-powered support and analytics using Microsoft Copilot, Zoho MCP and Zoho Zia to automate first responses, surface insights and reduce operational effort.',tags:['Microsoft Copilot','Zoho MCP','Zoho Zia','AI Copilot','98% L1 Resolution Reduction'],target:'#work-ai'},
 automation:{kicker:'AUTOMATION & SOFTWARE ASSET MANAGEMENT',title:'Automation — Process + Asset Efficiency',description:'Automation across software governance and Software Asset Management, including centralized inventory, compliance workflows, SOPs and operational controls.',tags:['Software Asset Management','100% Inventory Visibility','Compliance Automation','Software SOPs','25% Less Manual Verification'],target:'#work-sam'}
};
const servicePanel=document.querySelector('#servicePanel');const serviceTitle=document.querySelector('#serviceTitle');const serviceDescription=document.querySelector('#serviceDescription');const serviceKicker=document.querySelector('#serviceKicker');const serviceTags=document.querySelector('#serviceTags');const serviceLink=document.querySelector('#serviceLink');const serviceClose=document.querySelector('#serviceClose');const nodes=document.querySelectorAll('.service-node');
function openService(key){const d=serviceData[key];if(!d)return;nodes.forEach(n=>n.classList.toggle('selected',n.dataset.service===key));serviceKicker.textContent=d.kicker;serviceTitle.textContent=d.title;serviceDescription.textContent=d.description;serviceTags.innerHTML=d.tags.map(t=>`<span>${t}</span>`).join('');serviceLink.href=d.target;serviceLink.textContent='Explore related work ↗';servicePanel.classList.add('open');}
nodes.forEach(node=>node.addEventListener('click',()=>openService(node.dataset.service)));if(serviceClose)serviceClose.addEventListener('click',()=>{servicePanel.classList.remove('open');nodes.forEach(n=>n.classList.remove('selected'));});
const workflowTargets={implement:'#skills',automate:'#work-sam',secure:'#experience',monitor:'#work-itom',deliver:'#experience'};document.querySelectorAll('.workflow-step').forEach(step=>step.addEventListener('click',()=>{const target=workflowTargets[step.dataset.workflow];if(target)document.querySelector(target)?.scrollIntoView({behavior:'smooth',block:'start'});}));

function highlightWork(target){const card=document.querySelector(target);if(!card)return;card.classList.add('highlight');setTimeout(()=>card.classList.remove('highlight'),2200);}document.querySelectorAll('.service-node').forEach(node=>node.addEventListener('dblclick',()=>{const d=serviceData[node.dataset.service];if(d)highlightWork(d.target);}));